services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartconnect-crm-payload
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - media_data:/app/media

volumes:
  media_data: